name: build-reactables-core
run-name: ${{ github.actor }} is building the core reactable
on:
  workflow_dispatch:

jobs:
  get-extism:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: extism/js-pdk
      - run: sh install.sh
      - run: extism-js