name: build-reactables-core
run-name: ${{ github.actor }} is building the core reactable
on:
  workflow_dispatch:

jobs:
  get-extism:
    runs-on: ubuntu-latest
    env:
      TAG: v1.0.0-rc3
    steps:
      - uses: actions/checkout@v4

      - name: Setup Extism JS-PDK
        run: |
          curl -L -O "https://github.com/extism/js-pdk/releases/download/$TAG/extism-js-x86_64-linux-$TAG.gz"
          gunzip extism-js*.gz
          sudo mv extism-js-* /usr/local/bin/extism-js
          chmod +x /usr/local/bin/extism-js
          extism-js
      
      - name: Setup wasm-merge and wasm-opt
        run: |
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-linux.tar.gz > binaryen.tar.gz
          tar xvzf binaryen.tar.gz
          sudo cp binaryen-version_116/bin/wasm-merge /usr/local/bin
          sudo cp binaryen-version_116/bin/wasm-opt /usr/local/bin  
          # test it out
          wasm-merge